
services:
  db:
    image: postgres:14
    container_name: flights-db
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: flights
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flight-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flights
      - SPRING_DATASOURCE_USERNAME=flights
      - SPRING_DATASOURCE_PASSWORD=flights
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flight-frontend
    depends_on:
      - app
    ports:
      - "3001:80"
    restart: unless-stopped

volumes:
  pgdata:
